spring.application.name=cb-service
server.port = 8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/cherrybite
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
# Default schema
spring.jpa.properties.hibernate.default_schema=cb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect (optional for newer Spring Boot versions)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT configuration
jwt.secret=3r2o7h8f9k2m5q1w4v6b8n0x3z2c7a5rs
jwt.header=Authorization

server.servlet.context-path=/CB

#local storage path
app.upload.dir=uploads

#base url
app.base-url=http://localhost:8080

#spring profile
spring.profiles.active=local

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

